export interface ICurrency {
    name: string
    flag: string
}

const currencies: ICurrency[] = [
    { name: "AED - Emirati Dirham", flag: "🇦🇪" },
    { name: "AFN - Afghan Afghani", flag: "🇦🇫" },
    { name: "ALL - Albanian Lek", flag: "🇦🇱" },
    { name: "AMD - Armenian Dram", flag: "🇦🇲" },
    { name: "AOA - Angolian Kwanza", flag: "🇦🇴" },
    { name: "ARS - Argentine Peso", flag: "🇦🇷" },
    { name: "AUD - Australian Dollar", flag: "🇦🇺" },
    { name: "AWG - Aruban", flag: "🇦🇼" },
    { name: "AZN - Azerbaijan Manats", flag: "🇦🇿" },
    { name: "BAM - Bosnian Convertible Mark", flag: "🇧🇦" },
    { name: "BBD - Barbadian Dollar", flag: "🇧🇧" },
    { name: "BDT - Bangladeshi Taka", flag: "🇧🇩" },
    { name: "BGN - Bulgarian Leva", flag: "🇧🇬" },
    { name: "BHD - Bahraini Dinar", flag: "🇧🇭" },
    { name: "BIF - Burundian Franc", flag: "🇧🇮" },
    { name: "BMD - Bermudian Dollar", flag: "🇧🇲" },
    { name: "BND - Bruneian Dollar", flag: "🇧🇳" },
    { name: "BOB - Bolivian Bolíviano", flag: "🇧🇴" },
    { name: "BRL - Brazilian Real", flag: "🇧🇷" },
    { name: "BSD - Bahamian Dollar", flag: "🇧🇸" },
    { name: "BTN - Bhutanese Ngultrum", flag: "🇧🇹" },
    { name: "BWP - Botswana Pula", flag: "🇧🇼" },
    { name: "BYN - Belarusian Ruble", flag: "🇧🇾" },
    { name: "BZD - Belizean Dollar", flag: "🇧🇿" },
    { name: "CAD - Canadian Dollar", flag: "🇨🇦" },
    { name: "CDF - Congolese Franc", flag: "🇨🇩" },
    { name: "CHF - Swiss Franc", flag: "🇨🇭" },
    { name: "CLP - Chilean Peso", flag: "🇨🇱" },
    { name: "CNY - Chinese Yuan Renminbi", flag: "🇨🇳" },
    { name: "COP - Colombian Peso", flag: "🇨🇴" },
    { name: "CRC - Costa Rican Colon", flag: "🇨🇷" },
    { name: "CUC - Cuban Convertible Peso", flag: "🇨🇺" },
    { name: "CUP - Cuban Peso", flag: "🇨🇺" },
    { name: "CVE - Cape Verdean Escudo", flag: "🇨🇻" },
    { name: "CZK - Czech Koruna", flag: "🇨🇿" },
    { name: "DJF - Djiboutian Franc", flag: "🇩🇯" },
    { name: "DKK - Danish Krone", flag: "🇩🇰" },
    { name: "DOP - Dominican Peso", flag: "🇩🇴" },
    { name: "DZD - Algerian Dinar", flag: "🇩🇿" },
    { name: "EGP - Egyptian Pound", flag: "🇪🇬" },
    { name: "ERN - Eritrean Nakfa", flag: "🇪🇷" },
    { name: "ETB - Ethiopian Birr", flag: "🇪🇹" },
    { name: "EUR - Euro", flag: "🇪🇺" },
    { name: "FJD - Fijian Dollar", flag: "🇫🇯" },
    { name: "FKP - Falkland Island Pound", flag: "🇫🇰" },
    { name: "GBP - British Pound", flag: "🇬🇧" },
    { name: "GEL - Georgian Lari", flag: "🇬🇪" },
    { name: "GGP - Guernsey Pound", flag: "🇬🇬" },
    { name: "GHS - Ghanaian Cedi", flag: "🇬🇭" },
    { name: "GIP - Gibraltar Pound", flag: "🇬🇮" },
    { name: "GMD - Gambian Dalasi", flag: "🇬🇲" },
    { name: "GNF - Guinean Franc", flag: "🇬🇳" },
    { name: "GTQ - Guatemalan Quetzal", flag: "🇬🇹" },
    { name: "GYD - Guyanese Dollar", flag: "🇬🇾" },
    { name: "HKD - Hong Kong Dollar", flag: "🇭🇰" },
    { name: "HNL - Honduran Lempira", flag: "🇭🇳" },
    { name: "HRK - Croatian Kuna", flag: "🇭🇷" },
    { name: "HTG - Haitian Gourde", flag: "🇭🇹" },
    { name: "HUF - Hungarian Forint", flag: "🇭🇺" },
    { name: "IDR - Indonesian Rupiah", flag: "🇮🇩" },
    { name: "ILS - Israeli Shekel", flag: "🇮🇱" },
    { name: "IMP - Isle of Man Pound", flag: "🇮🇲" },
    { name: "INR - Indian Rupee", flag: "🇮🇳" },
    { name: "IQD - Iraqi Dinar", flag: "🇮🇶" },
    { name: "IRR - Iranian Rial", flag: "🇮🇷" },
    { name: "ISK - Icelandic Krona", flag: "🇮🇸" },
    { name: "JMD - Jamaican Dollar", flag: "🇯🇲" },
    { name: "JOD - Jordanian Dinar", flag: "🇯🇴" },
    { name: "JPY - Japanese Yen", flag: "🇯🇵" },
    { name: "KES - Kenyan Shilling", flag: "🇰🇪" },
    { name: "KGS - Kyrgyzstani Som", flag: "🇰🇬" },
    { name: "KHR - Cambodian Riel", flag: "🇰🇭" },
    { name: "KMF - Comorian Franc", flag: "🇰🇲" },
    { name: "KRW - South Korean Won", flag: "🇰🇷" },
    { name: "KWD - Kuwaiti Dinar", flag: "🇰🇼" },
    { name: "KYD - Caymanian Dollar", flag: "🇰🇾" },
    { name: "KZT - Kazakhstani Tenge", flag: "🇰🇿" },
    { name: "LAK - Lao Kip", flag: "🇱🇦" },
    { name: "LBP - Lebanese Pound ", flag: "🇱🇧" },
    { name: "LKR - Sri Lankan Rupee", flag: "🇱🇰" },
    { name: "LRD - Liberian Dollar", flag: "🇱🇷" },
    { name: "LSL - Basotho Loti", flag: "🇱🇸" },
    { name: "LYD - Libyan Dinar", flag: "🇱🇾" },
    { name: "MAD - Moroccan Dirham", flag: "🇲🇦" },
    { name: "MDL - Moldovan Leu", flag: "🇲🇩" },
    { name: "MGA - Malagasy Ariary", flag: "🇲🇬" },
    { name: "MKD - Macedonian Denar", flag: "🇲🇰" },
    { name: "MMK - Burmese Kyat", flag: "🇲🇲" },
    { name: "MNT - Mongolian Tughrik", flag: "🇲🇳" },
    { name: "MRU - Mauritanian Ouguiya", flag: "🇲🇷" },
    { name: "MUR - Mauritian Rupee", flag: "🇲🇷" },
    { name: "MVR - Maldivian Rufiyaa", flag: "🇲🇻" },
    { name: "MWK - Malawian Kwacha", flag: "🇲🇼" },
    { name: "MXN - Mexican Peso", flag: "🇲🇽" },
    { name: "MYR - Malaysian Ringgit", flag: "🇲🇾" },
    { name: "MZN - Mozambican Metical", flag: "🇲🇿" },
    { name: "NAD - Namibian Dollar", flag: "🇳🇦" },
    { name: "NGN - Nigerian Naira", flag: "🇳🇬" },
    { name: "NIO - Nicaraguan Cordoba", flag: "🇳🇮" },
    { name: "NOK - Norwegian Krone", flag: "🇳🇴" },
    { name: "NPR - Nepalese Rupee", flag: "🇳🇵" },
    { name: "NZD - New Zealand Dollar", flag: "🇳🇿" },
    { name: "OMR - Omani Rial", flag: "🇴🇲" },
    { name: "PAB - Panamanian Balboa", flag: "🇵🇦" },
    { name: "PEN - Peruvian Sol", flag: "🇵🇪" },
    { name: "PGK - Papua New Guinean Kina", flag: "🇵🇬" },
    { name: "PHP - Philippine Peso", flag: "🇵🇭" },
    { name: "PKR - Pakistani Rupee", flag: "🇵🇰" },
    { name: "PLN - Polish Zloty", flag: "🇵🇱" },
    { name: "PYG - Paraguayan Guarani", flag: "🇵🇾" },
    { name: "QAR - Qatari Riyal", flag: "🇶🇦" },
    { name: "RON - Romanian Leu", flag: "🇷🇴" },
    { name: "RSD - Serbian Dinar", flag: "🇷🇸" },
    { name: "RUB - Russian Ruble", flag: "🇷🇺" },
    { name: "RWF - Rwandan Franc", flag: "🇷🇼" },
    { name: "SAR - Saudi Arabian Riyal", flag: "🇸🇦" },
    { name: "SBD - Solomon Islander Dollar", flag: "🇸🇧" },
    { name: "SCR - Seychellois Rupee", flag: "🇸🇨" },
    { name: "SDG - Sudanese Pound", flag: "🇸🇩" },
    { name: "SEK - Swedish Krona", flag: "🇸🇪" },
    { name: "SGD - Singapore Dollar", flag: "🇸🇬" },
    { name: "SLL - Sierra Leonean Leone", flag: "🇸🇱" },
    { name: "SOS - Somali Shilling", flag: "🇸🇴" },
    { name: "SRD - Surinamese Dollar", flag: "🇸🇷" },
    { name: "SSP - Sudanese Pound", flag: "🇸🇩" },
    { name: "STN - Sao Tomean Dobra", flag: "🇸🇹" },
    { name: "SYP - Syrian Pound", flag: "🇸🇾" },
    { name: "SZL - Swazi Lilangeni", flag: "🇸🇿" },
    { name: "THB - Thai Baht", flag: "🇹🇭" },
    { name: "TJS - Tajikistani Somoni", flag: "🇹🇯" },
    { name: "TMT - Turkmenistani Manat", flag: "🇹🇲" },
    { name: "TND - Tunisian Dinar", flag: "🇹🇳" },
    { name: "TOP - Tongan Pa'anga", flag: "🇹🇴" },
    { name: "TRY - Turkish Lira", flag: "🇹🇷" },
    { name: "TTD - Trinidadian Dollar", flag: "🇹🇹" },
    { name: "TVD - Tuvaluan Dollar", flag: "🇹🇻" },
    { name: "TWD - Taiwan New Dollar", flag: "🇹🇼" },
    { name: "TZS - Tanzanian Shilling", flag: "🇹🇿" },
    { name: "UAH - Ukrainian Hryvnia", flag: "🇺🇦" },
    { name: "UGX - Ugandan Shilling", flag: "🇺🇬" },
    { name: "USD - US Dollar", flag: "🇺🇸" },
    { name: "UYU - Uruguayan Peso", flag: "🇺🇾" },
    { name: "UZS - Uzbekistani Som", flag: "🇺🇿" },
    { name: "VES - Venezuelan Bolívar", flag: "🇻🇪" },
    { name: "VND - Vietnamese Dong", flag: "🇻🇳" },
    { name: "VUV - Ni-Vanuatu Vatu", flag: "🇻🇺" },
    { name: "WST - Samoan Tala", flag: "🇼🇸" },
    { name: "ZAR - South African Rand", flag: "🇿🇦" },
    { name: "ZMW - Zambian Kwacha", flag: "🇿🇲" }
]

export default currencies;
